### ISSUE TITLE
Please replace st.experimental_get_query_params with st.query_params.

### ISSUE THREAD

**Issue by fsmosca** [WilianZilv/streamlit_superapp#1]
Please replace st.experimental_get_query_params with st.query_params.

st.experimental_get_query_params will be removed after 2024-04-11.

Refer to our [docs page](https://docs.streamlit.io/library/api-reference/utilities/st.query_params) for more information.

**Comment by A-BOVE** [comment]
Is it possible to push this update to the pypi project/pip installer?
